### ISSUE TITLE
[RESOURCE] A World at War by Bill McKibben

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#104]
### Resource title

A World at War by Bill McKibben

### URL

https://newrepublic.com/article/135684/declare-war-climate-change-mobilize-wwii

### Relevant tags (1 per line)

Politics/US
Article

### Resource Summary

An opinion piece from 2016 about the scope of climate action needed in the US, and an intro to climate policy PR messaging

### Relevance

Good inspirational content

**Comment by VeckoTheGecko** [comment]
We're not accepting individual articles or videos as resources in the knowledge hub:

* So many possible articles/videos that it would become untenable and drown out other resources
* Promoting a single piece can ommit different perspectives

I've created #173 to track changes to guidelines, which will be then reflected in the submission form

**Comment by JarrodBaniqued** [comment]
I will send in Bill McKibben's Substack (https://billmckibben.substack.com/about) as a potential replacement, considering it is also a newsletter in the style of Katharine Hayhoe's.
