### ISSUE TITLE
[YOUTUBER] Save Money Save the Planet

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#106]
### YouTube channel name

Save Money Save the Planet

### Channel link

https://www.youtube.com/c/SaveMoneySavethePlanet/about

### Channel ID

UCBKIpncsN7223P2zEATdPnw

### Description

Los Angeles-area netizen Nathan Kelcak, with the goal of getting viewers more in touch with the science and math behind climate change, reviews policy papers and shows how many climate solutions are actually way cheaper in the long run than our status quo, for both individuals and societies, in a quirky and optimistic way

**Comment by VeckoTheGecko** [comment]
We're updating the guidelines (#173), which means that small creators fall outside of the guidelines for adding YouTubers. This is still an open discussion.

Feel free to still submit smaller creators through the form. Although they'll be rejected for now, having a record here would allow for their potential inclusion in future.
