### ISSUE TITLE
[RESOURCE] terra.do: Online climate-focused job board and learning site

### ISSUE THREAD

**Issue by ForrestCinelli** [ClimateTown/knowledge-hub#109]
### Resource title

terra.do

### URL

https://terra.do/

### Relevant tags (1 per line)

Climate Careers
📚 Knowledge Hubs

### Resource Summary

Climate job board that also has lots of learning opportunities, seminars, and help to connect professionals breaking into the climate space. 

### Relevance

Jobs take 1/3 of our lives, so a website with an up-to-date job board plus extra goodies can help motivated members of the community find a way to make a difference.

**Comment by VeckoTheGecko** [comment]
Looks awesome! Thanks for the suggestion
