### ISSUE TITLE
[RESOURCE] NASA WorldView (EOSDIS) - Daily NASA satellite imagery with plenty of overlays and historical data

### ISSUE THREAD

**Issue by GBT7** [ClimateTown/knowledge-hub#111]
### Resource title

NASA WorldView (EOSDIS)

### URL

https://worldview.earthdata.nasa.gov/

### Relevant tags (1 per line)

Tools

### Resource Summary

The NASA Worldview app provides satellite imagery of earth as it looks today and in the past through daily satellite images. Includes data on fires, droughts, floods, storms, pollution, and vegetation, with the ability to overlay, animate, and download the data.

### Relevance

It provides easy visuals for tracking things such as more frequent and severe environmental catastrophes, such as wildfires

**Comment by VeckoTheGecko** [comment]
Great suggestion!

> it could probably use more tags

Applying relevant tags from the existing set is encouraged. But we do err on not creating new tags (unless the resource goes in a whole new direction, where there is a lot of opportunity for useful resources in a similar vein. e.g. recently with `Climate Accountability` and `Climate Journalism`). I think `Maps` as a tag may only have this one resource/a few resources.
