### ISSUE TITLE
[RESOURCE] En-ROADS - an in-browser real time simulation graphs for modeling global warming reductions

### ISSUE THREAD

**Issue by GBT7** [ClimateTown/knowledge-hub#112]
### Resource title

En-ROADS

### URL

https://en-roads.climateinteractive.org/

### Relevant tags (1 per line)

Tools
Climate Models

### Resource Summary

A resource developed by MIT and Climate Interactive to visualize how various factors can steer the climate. You can move sliders to change the outcomes based on factors such as energy supply, transport, industry, and more.

### Relevance

It is an interactive climate model with a low barrier to use

**Comment by VeckoTheGecko** [comment]
Great resource!
