### ISSUE TITLE
[RESOURCE] Climate Action Tracker - Data on which governments are keeping their promises, and if their promises are adequate

### ISSUE THREAD

**Issue by GBT7** [ClimateTown/knowledge-hub#114]
### Resource title

Climate Action Tracker

### URL

https://climateactiontracker.org/

### Relevant tags (1 per line)

Politics/Global
Climate Accountability

### Resource Summary

Tracks the climate action promises made by politicians across the world, whether they are being kept, and whether they are adequate.

### Relevance

It is a Climate Action Tracker.

**Comment by VeckoTheGecko** [comment]
I think this is an opportunity to mint a new tag: `Climate Accountability`!

Thanks for the suggestion.
