### ISSUE TITLE
[RESOURCE] Breakthrough Energy Ventures job board

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#116]
### Resource title

Breakthrough Energy Ventures job board

### URL

https://bevjobs.breakthroughenergy.org/jobs

### Relevant tags (1 per line)

Climate Careers

### Resource Summary

Search job openings across the Breakthrough Energy Ventures network, an initiative founded by Bill Gates.

### Relevance

Job site related to climate, **though the Bill Gates/Jeff Bezos/Ray Dalio/Reid Hoffman/Michael Bloomberg/David Rubenstein/John Doerr/Vinod Khosla/Richard Branson funding might not make this palatable for everyone**

**Comment by VeckoTheGecko** [comment]
Good suggestion!
