### ISSUE TITLE
[RESOURCE] The Gigaton

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#117]
### Resource title

The Gigaton

### URL

https://thegigaton.substack.com/

### Relevant tags (1 per line)

Climate Careers
Climate Journalism
Education

### Resource Summary

A newsletter to help climate newbies identify careers with the highest carbon emission impact. Written by Stanford MBA students Stella Liu, Joseff Kolman, and Georgia Kossoff.

### Relevance

Part careers blog, part tech solutions news magazine, all inclusive

**Comment by VeckoTheGecko** [comment]
Great suggestion. Just a note that normally the `og:description` tag in the website is often a really good way to get these resource summaries (i.e. go to the website, open web tools (Ctrl+Shift+C), search (Ctrl+F) for `og:description`, copy and adapt text).

Updated your post with new description and removing `Knowledge Hubs` tag (which is reserved for specific types of resources).
