### ISSUE TITLE
[RESOURCE] Amazon Climate Pledge Fund jobs site

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#118]
### Resource title

Climate Pledge Fund jobs site

### URL

https://portfoliojobs.theclimatepledge.com/jobs

### Relevant tags (1 per line)

Climate Careers

### Resource Summary

Search job openings across the Amazon Climate Pledge network.

### Relevance

Job site for climate careers; **use with caution**

**Comment by VeckoTheGecko** [comment]
Thanks for the suggestion. Just clarifying a few things:

* How sure are you of the usefulness of this resource (is just greenwashing?). Briefly looking online it doesn't look great ([link1](https://www.stern.nyu.edu/experience-stern/about/departments-centers-initiatives/centers-of-research/center-sustainable-business/news-events/news-insights/amazon-s-climate-pledge-greenwashing), [link2: article](https://www.nbcnews.com/select/shopping/amazon-climate-pledge-ncna1271192))
* I can't see a jobs board here? Is it behind a login or something? If so please update summary with this info.
* I don't think the `📚Knowledge Hubs` tag is used properly here. That tag is reserved for initiatives like the Climate Town Knowledge Hub (i.e. lots of linking of resources). These other knowledge hubs have the potential to be more niche focussing in one area. 
* Markdown format, and links aren't supported for the resource summary, only text (the resource summary is displayed directly on the Knowledge Hub website in the cards for the resource).

Please edit your original post above to adress these. Keen to know what you think 😄

**Comment by JarrodBaniqued** [comment]
> * How sure are you of the usefulness of this resource (is just greenwashing?).

Unsure now that you bring it up. I must add the context of the recent [Oregon bill](https://www.washingtonpost.com/technology/2023/04/04/amazon-climate-energy-fuel-oregon/) Amazon lobbied against even though it lined up with the 2040 pledge. The only way I came across it in the first place was in a _New York Times_ newsletter about The Gigaton. I recommend conferring with others to discuss the matter before deciding whether or not to approve. If I committed any oversight of fact-checking, I deeply apologize. 

> * I can't see a jobs board here? Is it behind a login or something? If so please update summary with this info.

It is not behind a login, last I checked, and the entries showed up fine on Safari. 

> * I don't think the `📚Knowledge Hubs` tag is used properly here. That tag is reserved for initiatives like the Climate Town Knowledge Hub (i.e. lots of linking of resources). These other knowledge hubs have the potential to be more niche focussing in one area. 

Understood, and fixed. Apologies for breaking any unspoken norms about which tags go where.

> * Markdown format, and links aren't supported for the resource summary, only text (the resource summary is displayed directly on the Knowledge Hub website in the cards for the resource).

I see. Didn't know until now, thanks.

**Comment by VeckoTheGecko** [comment]
> If I committed any oversight of fact-checking, I deeply apologize.

Na, its all good. The goal of these issues is to have that open discussion and to further investigate before including. I think Amazon (justifiably) has a pretty bad wrap so just want to make sure we look into it more before adding.

If the resource is genuinely useful, then I think its fine to include (even if it could be greenwashing). As long as the summary mentions its an initiative by Amazon.

Will discuss this in Discord.

> Apologies for breaking any unspoken norms about which tags go where

All good. Was mainly just letting you know. One of the problems with the site at the moment is that the rules around tags are unspoken (which we'll hopefully fix in future with a section explaining the tags). Rule of thumb: If it has an emoji, its a special one.

**Comment by JarrodBaniqued** [comment]
You're very welcome, glad to help if I can

**Comment by VeckoTheGecko** [comment]
Discussed with some other mods, and its alright. Criticism can be levelled at Amazon, and potentially the Fund, but the jobs board is more about positions with other climate companies so its alright.
