### ISSUE TITLE
[FEATURE] Suggest resource/edit resource button positioning

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#120]
**Describe your suggested improvement**
Change positioning of "Suggest resource" and "edit resource" buttons on the resource page to be outside the filter modal (as they do not apply to the filter).

Medium priority here (instead of low) as accessibility is important., Currently these buttons aren't mobile friendly.

Proposed repositioning:
![image](https://user-images.githubusercontent.com/36369090/236675873-9a1453f8-5032-4a13-bde6-8dce3c2c0840.png)

Its important that the buttons are still very accessible (i.e. appear above the resources).

**Describe the benefit**
Better UI

**Would you be capable/willing to implement the improvement?**
No. Original suggester may be interested (and if not, someone else is welcome to tackle this).

**Additional comments**
Suggested by `dmlb#4735` on Discord.

**Comment by dmlb** [comment]
🙂

**Comment by williamtaggart97** [comment]
Hi @VeckoTheGecko, I just found your repo and would love to contribute. Can I give this a shot?

**Comment by VeckoTheGecko** [comment]
Of course 😁. If you have webdev skills and want to do some more contributions beyond this issue, I'm thinking of making more issues around various UI elements that are buggy at the moment. Let me know if you're interested/have ideas

**Comment by williamtaggart97** [comment]
Yep, sounds good. React developer by trade but interested in svelte :)
