### ISSUE TITLE
[RESOURCE] Ecosia

### ISSUE THREAD

**Issue by tutterown** [ClimateTown/knowledge-hub#125]
### Resource title

Ecosia

### URL

https://ecosia.org/

### Relevant tags (1 per line)

Tools

### Resource Summary

Ecosia uses the ad revenue from your searches to plant trees where they're needed most. Also has tooling for quickly spotting websites belonging to climate friendly, and climate polluting companies.

**Comment by azebramoomoo** [comment]
Another thing to add maybe is how it also tells you about certain companies and how well they are doing when it comes to climate and stuff and how it gives them scores so you can see just from the results page

**Comment by azebramoomoo** [comment]
![1B4A8734-31B5-4C6A-9DDE-B08D91FC6605](https://user-images.githubusercontent.com/121310825/236714099-16e8f909-7de3-4a33-a4a8-85b7dfb47e84.jpeg)
 
 I should note it also has this feature when a link is by a fissile fuel company as you can see in this screenshot

**Comment by JarrodBaniqued** [comment]
I've seen mixed reviews in the comment section of Charlie from Our Changing Climate's video on Ecosia (for what it's worth, Charlie gives Ecosia a good review). https://www.youtube.com/watch?v=z1AVgbI_1r0 There's also this blog that gives Ecosia a glowing review but notes some caveats. https://cariki.co.uk/blogs/the-green-road/is-ecosia-legit-or-fake

**Comment by VeckoTheGecko** [comment]
Accepted. Thanks for the info @azebramoomoo , added to description.
