### ISSUE TITLE
[CORRECTION] Copy edits to adhere to AP Stylebook

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#127]
**Corrections**
I recommend using the _AP Stylebook_ (https://www.apstylebook.com) for all copy editing decisions from now on. I would also recommend labeling this issue "low-priority".
1. In the description for The Greenlining Institute, replace the word "are" with "get".
2. For RMI, replace "who's" with "whose" and "orginization" with "organization".
3. For 12ft.io, replace "payways" with "paywalls".
4. For Common Cause, the first letter in the word "Cause" should be capitalized.
5. For Awesome Earth, replace "currated" with "curated", and hyphenate "open source" if the AP Stylebook recommends it.
6. For 80,000 Hours, add "so" between the last comma and "why".
7. For FruitPunch AI, hyphenate "change oriented".
8. For Cronometer, hyphenate "feature rich".
9. For Challenge 22 and Veganuary, hyphenate "plant based".
10. For the US National Snow and Ice Data Center, hyphenate "up to date".
11. For Earth Nullschool, hyphenate "easy to use".
12. For Carbon Brief, replace "whats" with "what's".
13. For the UFCW, add an apostrophe to the right of "workers".
Also, I would suggest adding "Written by Stanford MBA students Stella Liu, Joseff Kolman, and Georgia Kossoff." to the description for The Gigaton, and including John Doerr's name somewhere in the description for Speed and Scale.

**Comment by VeckoTheGecko** [comment]
I think standardising language in this context sounds like a good idea.

I am too small brained in the English department to work on this though, and it might be easier for you to make the changes yourself. Making tweaks like this can be easily done. You can [click this link](https://github.com/ClimateTown/knowledge-hub/edit/main/data/resources.yml) which will bring you straight to an editing window. More generally, to edit files you:

* Browse to the file in GitHub
* Press the [pencil icon](https://user-images.githubusercontent.com/36369090/236850816-94bdbf12-3cf6-482c-97e2-3470070f487c.png)

Let me know if you have any difficulties, and we can come up with another solution.
