### ISSUE TITLE
[FEATURE] Reverse chronological resource ordering

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#130]
**Describe your suggested improvement**
Currently the order of the resource list in the website mirrors the resource list in `data/resources.yml` (i.e. resources are added to the bottom of the `.yml` file and also displayed at the bottom of the website.

Reversing this (so newer resources appear at the top of the website) would allow people to quickly check back to the site and see if new resources have been added.

**Describe the benefit**  
Highlights the dynamic nature of the site, and rewards users who visit regularly with the new resources they're looking for.

**Would you be capable/willing to implement the improvement?**
Good first issue for someone wanting to get involved. If nobody claims it, will make a PR for it this weekend.

**Other comments**

Data is loaded in here. `yml_data` is a list of objects (as represented in the YAML file.

https://github.com/ClimateTown/knowledge-hub/blob/36f3a98c6255554789733262a83281285fcb7ec2/src/routes/resources/+page.server.ts#L7-L10

**Comment by Micahg05** [comment]
Ill do this real quick. Good warmup for the PR process and building the project.

**Comment by Micahg05** [comment]
@VeckoTheGecko since the data doesn't contain a time to key off of newest vs oldest items is the ongoing assumption going to be that its always just a reverse order of the array?
