### ISSUE TITLE
[FEATURE] Add broken link checker and issue bot

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#14]
Add [broken link checker](https://github.com/marketplace/actions/broken-link-check) and [issue bot](https://github.com/marketplace/actions/issue-bot-action) to create a GitHub issue when a broken link is seen in a build

**Am I willing to work on this?**
Not currently. Happy for someone else to take the torch on this one.

**Comment by Morzaram** [comment]
@VeckoTheGecko - I was thinking of using node cron and just doing a sweep on a daily basis if you want? Do you have any implementation details?

**Comment by VeckoTheGecko** [comment]
I was thinking a GH Actions workflow that is cron scheduled calling a script would be a good way to go about it (I'm not sure how node cron works, but I think that might be a less elegant implementation?).

Implementation details:
- Check for non `2xx` codes (e.g. we're also interested in 301 (domain moved) for example so we can update the links)
- Weekly cron (less spammy in case there's a website that temporarily goes down for a few days)
- A way of surfacing failing links (easy: Failing CI/CD; hard: automatic creation of GitHub issue)
- Python preffered (although that's a soft requirement. If the implementation code is clean then I'm happy for it to be any language (please not golfscript))

Feel free to discuss any of those details. They're not hard and fast.
