### ISSUE TITLE
[FEATURE] Add toggle to allow user to search tags with OR logic or AND logic

### ISSUE THREAD

**Issue by williamtaggart97** [ClimateTown/knowledge-hub#141]
**Describe your suggested improvement**
Right now, I can only search for one particular topic at a time. I want to change the search logic for tags to represent searching for tag1 or tag2 instead of tag1 and tag2.

**Describe the benefit**
For instance, I tried to search for Article + Climate Tech and nothing came up -- but I think it would be helpful to have that be represented as Articles or Climate Tech resources so that the user is more likely to see results.

**Would you be capable/willing to implement the improvement?**
Yes

**Additional comments**
Please let me know if this is something you would want me to change! I'll start working on the change in the meantime. In the long run, I could add a more complex search that allows for both and/or logic and potentially separates tags into categories, etc.

CODE REFERENCE LOCATION: 
[filterResources Location](https://github.com/ClimateTown/knowledge-hub/blob/c39e88f008f7443a9b48987c2328cc41886d84b9/src/routes/resources/%2Bpage.svelte#LL26C26-L26C26)

**Comment by VeckoTheGecko** [comment]
Do you think it would be easy to implement a toggle UI element in the filters where one way it goes into OR mode, and the other way into AND mode?

From my POV, I envision the resource base will grow considerably to the point where browsing under a single tag could be overwhelming and browsing the intersection of multiple tags (i.e. AND) would be better. For example, someone interested in Australian Climate Journalism could look at `Climate Journalism` AND `Location/Australia`

Having the option to do either AND or OR (browsing narrow, or wide) is ideal, and would be a really welcome PR. If I had to choose one between AND or OR, I'd lean towards AND in the long-term (browsing wide is a pain, but at least browsing narrow is *possible*, where browsing narrow with OR isn't possible).

**Comment by williamtaggart97** [comment]
Yea that makes sense, I'm looking through and I think I found the code needed to change for AND vs OR. I can build in the toggle as well.
