### ISSUE TITLE
[YOUTUBER] EcologistAlana

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#144]
### YouTube channel name

EcologistAlana

### Channel link

https://www.youtube.com/channel/UCotgZmSlreKO_ELcV01-j_g

### Channel ID

UCotgZmSlreKO_ELcV01-j_g

### Description

Cornish ecologist and naturalist Alana Scott discusses the benefits of conservation, rewilding and various other topics related to the environment, particularly of Britain.

**Comment by VeckoTheGecko** [comment]
Same as https://github.com/ClimateTown/knowledge-hub/issues/106#issuecomment-1546819336
