### ISSUE TITLE
[RESOURCE] Climate Case Chart

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#167]
### Resource title

Climate Case Chart, by the Sabin Center

### URL

http://climatecasechart.com/

### Relevant tags (1 per line)

Climate Accountability
Research

### Resource Summary

A database of information and case documents for over 1000 climate change lawsuits from around the world, hosted by the Sabin Center for Climate Change Law at Columbia University.

### Relevance

Important for tracking an emerging field of climate action: judicial policymaking.

**Comment by VeckoTheGecko** [comment]
Great resource!
