### ISSUE TITLE
[YOUTUBER] Robert at Children’s Climate Championship

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#170]
### YouTube channel name

Robert at Children’s Climate Championship

### Channel link

https://www.youtube.com/@robertatchildrensclimatech9371/about

### Channel ID

UCCzJK4HEaoEnxoIyCBtb52Q

### Description

Toronto-based climate activist Robert talks to children around the world about climate change, and to scientists, charities, companies and activists about what kids can do to help, and rewards carbon negative countries.

**Comment by VeckoTheGecko** [comment]
Same as https://github.com/ClimateTown/knowledge-hub/issues/106#issuecomment-1546819336
