### ISSUE TITLE
[ORGANIZATION] Center for Biological Diversity

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#177]
### Resource title

Center for Biological Diversity

### URL

https://www.biologicaldiversity.org/about/

### Relevant tags (1 per line)

Organizations
Politics/US

### Resource Summary

A nonprofit focused on legal protection of endangered species and wildlife, plus some energy justice work. Founded in 1989 by Kieran Suckling, Peter Galvin, Todd Schulke and Robin Silver.

### Relevance

A nonprofit with good coverage of endangered species and conservation efforts and decades of experience

### Other comments

https://www.biologicaldiversity.org/programs/energy-justice/pdfs/Policy-Brief-for-Positive-Vision.pdf for archive purposes

**Comment by VeckoTheGecko** [comment]
Sorry about the long response time on this.



> Their [plan for renewable energy justice](https://www.biologicaldiversity.org/programs/energy-justice/pdfs/Policy-Brief-for-Positive-Vision.pdf) is recommended policy inspiration.

I think with the resource summaries it would be good to stray from wording that is a personal recommendation. Would you mind rewording that? (I'm not familiar with their work, so I don't think I'd do it justice). Also the "Resource Summary" section can't have links in it as the site doesn't support it (but feel free to bump that into `Other comments` so its still visible on this issue).

**Comment by JarrodBaniqued** [comment]
> Would you mind rewording that? (I'm not familiar with their work, so I don't think I'd do it justice). Also the "Resource Summary" section can't have links in it as the site doesn't support it (but feel free to bump that into `Other comments` so it's still visible on this issue).

Done.

**Comment by VeckoTheGecko** [comment]
Thanks @JarrodBaniqued !

**Comment by VeckoTheGecko** [comment]
Resource added in 85d1c68
