### ISSUE TITLE
[RESOURCE] Hill Heat

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#196]
### Resource title

Hill Heat

### URL

http://www.hillheat.com/pages/about/

### Relevant tags (1 per line)

Climate Journalism
Climate Accountability
Research
Politics/US

### Resource Summary

Summaries of the latest in climate policy, including in the U.S. Congress, as well as key elections at all levels of government. Edited by Brad Johnson.

### Relevance

Important info on climate and congressional action

**Comment by tutterown** [comment]
I've added this in #210 . FYI, I changed it to use `HTTPS`
