### ISSUE TITLE
[FEATURE] Remove shorts from YouTube feed

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#200]
**Describe your suggested improvement**
Remove YouTube shorts from the YouTube feed.

**Possible implementation**  
If the YouTube API has info on whether the video is a short (either by a flag, or by video duration/video orientation which might be used to determine if something is a short), this can be used to filter out the shorts content in the YouTube scraping script.

**Describe the benefit**
As we add more YouTubers to the feed, short form content has the potential to take over the feed. It would be good to focus on long form content which is often higher quality, and more informative than short form. Also if people want to watch targeted short form content, they'd just use TikTok/YouTube Shorts anyway.

**Would you be capable/willing to implement the improvement?**
Perhaps. I'm also keen for someone else to take the lead on this.

**Comment by macaugh** [comment]
Taking a look at this. It appears that the standard Youtube API does not have a field indicating shorts vs standard. Options I see are either an open source API or a 300 redirect check on youtube.com/shorts/+video.

**Comment by VeckoTheGecko** [comment]
Do open source APIs for YouTube exist? If so, that could also help with #214.

I think a redirect check on `youtube.com/shorts/+video` would probably be the easiest implementation since the video ID would be returned.
