### ISSUE TITLE
[FEATURE] Filter modularization into Svelte components

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#209]
**Describe your suggested improvement**
The [resources page](https://climatetown.github.io/knowledge-hub/resources) and [YouTube feed](https://climatetown.github.io/knowledge-hub/youtube) both have filters that are almost identical, however their implementation involves copy-paste code duplication between the `src/routes/youtube/+page.svelte` and `src/routes/resources/+page.svelte`  files.

Refactoring this into a Svelte component that can be used in both pages would be great to reduce duplication.

**Describe the benefit**
Code quality.

**Would you be capable/willing to implement the improvement?**
No

**Additional comments**
This issue would require some confidence in Svelte/willingness to learn.

**Comment by dmlb** [comment]
closed by https://github.com/ClimateTown/knowledge-hub/pull/263 ?

**Comment by VeckoTheGecko** [comment]
> closed by #263 ?

Good point, but I'd say #263 only partially contributes to it. There is still duplication in the filtering functions in the filter that would be good to clean up into separate functions in `lib`

**Comment by VeckoTheGecko** [comment]
Superceded by #299
