### ISSUE TITLE
[FEATURE] Standardize Resource Card Height

### ISSUE THREAD

**Issue by williamtaggart97** [ClimateTown/knowledge-hub#221]
**Describe your suggested improvement**
I would love to have a more standardized resource card height so that it looks cleaner as we scroll through the site

<img width="986" alt="Screenshot 2023-05-23 at 2 55 20 PM" src="https://github.com/ClimateTown/knowledge-hub/assets/49992113/28a18e06-7966-4314-9eff-017a01499ff3">

**Would you be capable/willing to implement the improvement?**
Yes

**Comment by VeckoTheGecko** [comment]
Yes please! Especially if it's done row by row 🤩 (hopefully there's CSS for that)

**Comment by VeckoTheGecko** [comment]
*(Coming from a bad UI designer)* I don't think fixing card heights without introducing weird looking whitespace is possible. If you find a way to do so, please submit a Figma mockup prior to a PR (for easier feedback and quicker iterations).

See more at https://github.com/ClimateTown/knowledge-hub/pull/224#issuecomment-1568713957.

**Comment by williamtaggart97** [comment]
that's a good point, what if we used an overflow like with an ellipsis (...) to standardize card heights

**Comment by VeckoTheGecko** [comment]
There are already hard limits in place for description length (<300 char). I don't want to pose another one in the UI. I would rather have inconsistent card heights than incomplete descriptions.

**Comment by dmlb** [comment]
> There are already hard limits in place for description length (<300 char). I don't want to pose another one in the UI. I would rather have inconsistent card heights than incomplete descriptions.

is there a maximum on the title also?

**Comment by VeckoTheGecko** [comment]
Yes, and the tags. Everything is encoded in the resource.schema.json file

**Comment by dmlb** [comment]
@williamtaggart97 @VeckoTheGecko 
Instead of a fixed height, here I have each card grow into the height of the grid row then flex the tags towards the bottom; you'll see some space between description and tags when short descriptions on the same row as a long one:
https://github.com/ClimateTown/knowledge-hub/pull/243
