### ISSUE TITLE
[RESOURCE] Strong Towns

### ISSUE THREAD

**Issue by Lasercar** [ClimateTown/knowledge-hub#239]
### Resource title

Strong Towns

### URL

https://www.strongtowns.org/

### Relevant tags (1 per line)

Climate Journalism

### Resource Summary

Strong Towns is a nonprofit media advocacy organization founded by civil engineer Chuck Marohn. They produce content that analyzes the failures of the post-war North American development pattern while giving people the knowledge and tools to start making their places better today.

### Relevance

Car dependency bad

**Comment by JarrodBaniqued** [comment]
I endorse this resource, provided there is an “a” between “is” and “nonprofit”, and “founded by civil engineer Chuck Marohn” after “organization”.
