### ISSUE TITLE
[RESOURCE] Project InsideOut

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#256]
### Resource title

Project InsideOut

### URL

https://projectinsideout.net/about/

### Relevant tags (1 per line)

Healthy Living
Education

### Resource Summary

An online hub where environmentalists and clinical psychologists come together to focus on providing tools for sustainable behavior change. Founded in 2022 by Renée Lertzman.

### Relevance

A good, evidence-based guide to activist outreach and empathizing with climate skeptics

**Comment by VeckoTheGecko** [comment]
Thanks for the resource! As someone more famliar with the resource, could you explain the selection of the "Collective Action" tag choice a bit more? That tag is more reserved for active communities that people can join (e.g. take part in projects, join makers spaces, etc), not 100% sure if this fits in that tag?

A bit more info for the Activism tag would be welcome too.

Removing the `📚 Knowledge Hubs` tag as that is reserved for initiatives like the this Knowlege Hub (i.e., linking to various climate resources (mainly online websites) made by different people/orgs).

Just paying attention to detail here to get it right, as when its added it will be more effort to re-assess the tags 😄

**Comment by VeckoTheGecko** [comment]
Yeah, I think a general rule of thumb for some of these tags is that if you have to dig deep into the site to justify a tag, it probably isn't a good fit.

The `Activism` tag is mainly for activism orgs and more direct activist resources.

Thanks for the speedy response! Updated the tags, will now onboard these 🤩🤩
