### ISSUE TITLE
[BUG] YouTuber filter

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#274]
**Describe the bug**
The YouTubers filter does not work in Safari mobile; when deselecting all but one channel, the video list stays the same

**To Reproduce**
Steps to reproduce the bug:

1. Go to YouTubers page
2. Tap any channel
3. Scroll down to list

**Expected behavior**
The selections' videos would have been shown immediately

**Comment by VeckoTheGecko** [comment]
Thanks for flagging!

@all-contributors please add @JarrodBaniqued for bug
