### ISSUE TITLE
[FEATURE] Clear All Filters Button

### ISSUE THREAD

**Issue by williamtaggart97** [ClimateTown/knowledge-hub#284]
**Describe your suggested improvement**
I would love a button that can clear all filters and refresh the resources/videos. Especially as the dataset gets bigger and we are more likely to have multiple filters it can be a bit tedious to reset my filter.

**Describe the benefit**
This would make it easier for Users to find resources they are interested in and explore the different resources available.

**Would you be capable/willing to implement the improvement?**
YES

**Additional comments**
I will provide screenshots of the added design when I create a PR.

**Comment by VeckoTheGecko** [comment]
This feature suggestion read my mind 🤯

**Comment by VeckoTheGecko** [comment]
just an FYI @williamtaggart97 looks like we recently have a PR in for this issue as well. Just so you know

**Comment by williamtaggart97** [comment]
@VeckoTheGecko thanks! So I'm actually working with a group of developers (we're using Open-Source repos to hone our skills and best practices) and I think one of our developers put up that PR. We're training on Typescript as well so this has been a great repo to contribute to _(thanks for everything you do to maintain it)_ !

**Comment by VeckoTheGecko** [comment]
Oh thats awesome! That context does help, I thought it was just people picking up PRs spontaneously 😋. Great to have active contributors

**Comment by VeckoTheGecko** [comment]
Completed in #285
