### ISSUE TITLE
[RESOURCE] Atmos Financial

### ISSUE THREAD

**Issue by rivermizell** [ClimateTown/knowledge-hub#286]
### Resource title

Atmos Financial

### URL

https://www.joinatmos.com/

### Relevant tags (1 per line)

🍞 Rollie's Choice
Finance
location/US

### Resource Summary

Atmos is the world's most sustainable checking and savings accounts. All deposits are used for climate positive projects like solar for all. FDIC insured, climate cash back, high-yield savings, and solar loans.

### Relevance

Atmos is funding the transition to a climate positive future and away from fossil fuel funding traditional banks support.

**Comment by VeckoTheGecko** [comment]
I updated the tags and removed the image (the image is manually customisable in the hub, instead pulling the thumbnail image set by the website creators). Looks great!

**Comment by rivermizell** [comment]
Thanks so much!
