### ISSUE TITLE
[FEATURE] Add custom error page

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#29]

**Comment by VeckoTheGecko** [comment]
Clearing assignee in case someone else wants to give this a stab. If anyone starts development, please post a comment here to discuss approach (and look of the 404 page) 🙂

**Comment by tutterown** [comment]
@VeckoTheGecko Any ideas on what we may want the page to look like? I can create a standard error page that will give a standard response. It's as simple as creating a `+error.svelte` file in the `routes` directory as shown [here](https://kit.svelte.dev/docs/routing#error). Doing this would just give an error from the Climate Town page rather than the Github Pages error that currently appears.

**Comment by tutterown** [comment]
Here's an example of what it would look like. I can also have it just use the default error message `404: Not Found`.

Note: This is a dynamic page that should catch any type of error, not just 404s. If we want to customize the 404 page specifically, I believe it would be a bit more involved. 
![svelteerror](https://github.com/ClimateTown/knowledge-hub/assets/1977859/e568ef01-529b-4ebc-98c2-772d92c7d4c5)

**Comment by VeckoTheGecko** [comment]
Updated title to match. The site at the moment doesn't yet have a unified style (#70), so I'm not particular about the look of the error page. If you want to design something with CSS, then somewhat fitting within the general themes of the site (climate, knowledge) and having it look good would be the only requirements.

Having the simple error page you've already implemented is a great addition anyway, and enough to close this issue.

Just know if you do a custom CSS design that someone working on #70 may redo the page as part of the site redesign.

**Comment by VeckoTheGecko** [comment]
Hmm. I'm not sure if this is working after merging #171 @tutterown?

https://climatetown.github.io/knowledge-hub/test

**Comment by VeckoTheGecko** [comment]
Hmmm. In the build process all Svelte pages get converted to HTML, so a `404.html` page should be created.

I'll check the build process to ensure an error page is created.

It might be something to do with it being served from https://climatetown.github.io/knowledge-hub and not a root domain.

**Comment by VeckoTheGecko** [comment]
**An conclusive investigation?**

A preliminary search led me to [this Stackoverflow answer](https://stackoverflow.com/a/14908632) from 2013 mentioning that 404s can only be served from root domains. Given the age of this article, and the fact that there is no mention on this is the [current custom 404 help article](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site) leads me to believe that this is no longer an issue.

Instead, I think the source of the issue is in how Svelte Kit renders the static site. Using `npm run dev` a dev server is spun up on `localhost`, which handles the requests (and hence serves the appropriate `404` page from `+error.svelte`). However, running `npm run build` doesn't create a `404.html` page in `build`. Searching, I found this issue https://github.com/sveltejs/kit/issues/1172 , which links to another mentioning that the action to take is adding a `fallback` option to `svelte.config.js`.

From our config:
```diff
const config = {
    preprocess: vitePreprocess(),
    kit: {
        adapter: adapter({
            pages: 'build',
            assets: 'build',
-           fallback: null,
+           fallback: "404.html",
            precompress: false
        }),
        alias: { 'lib/': './src/lib/' },
        prerender: {
            entries: ['*']
        },
        paths: {
            base: dev ? '' : '/knowledge-hub',
        },
    }
};
```

Doing this, and running `npm run build` a `404.html` page is now generated. I'll open a PR for this sometime soon (unless someone beats me to it).
