### ISSUE TITLE
[FEATURE] Build a reusable search component, similar to a modularized filter component

### ISSUE THREAD

**Issue by williamtaggart97** [ClimateTown/knowledge-hub#296]
**Describe your suggested improvement**
It would be nice to add a traditional search bar to filter resources and videos (rather than only filter on tags/channels). I am open to suggestions on what fields should be searchable. Also, we can start this functionality on the front-end but eventually the searching could happen on the backend and we can build this to make sure that transition is "seamless".

**Describe the benefit**
Users are more easily able to find relevant resources. 

**Would you be capable/willing to implement the improvement?**
Yes but I might not have time this week

**Additional comments**
@VeckoTheGecko let me know if you have any thoughts on how this should interact with the data.

**Comment by VeckoTheGecko** [comment]
I think this is a good idea (particularly for the resources page. The YouTube page would have minimal benefit as people don't search for individual videos, but mainly YouTubers and theres already filtering for that).

A few thoughts:
- **An off the shelf search integration would be great and likely produce a higher quality search** (e.g. allowing for fuzzy maching which would be a pain to code manually). This would also reduce code debt in the project. Perhaps you could look into existing open source solutions that can be integrated into the platform? Let me know if you want me to look
- **I'm not sure what you mean by "back end"**. This platform is a statically hosted website, so its all just HTML, CSS and Javascript which is bundled and shipped to the client. There is no backend server.

I think once I (or someone else willing) am able to make progress on #299, adding new features like this will hopefully be more clearcut in terms of the organisation of the project

**Comment by williamtaggart97** [comment]
I can look into an OTS search option. There are definitely some libraries out there that can do this well. 

Right, no backend so no worries there 👍
