### ISSUE TITLE
[RESOURCE] Climate Analytics

### ISSUE THREAD

**Issue by themonarchofsquarks** [ClimateTown/knowledge-hub#313]
### Resource title

Climate Analytics

### URL

https://climateanalytics.org/

### Relevant tags (1 per line)

Climate Journalism

### Resource Summary

Climate Analytics is a global climate science and policy institute engaged around the world in driving and supporting climate action aligned to the 1.5°C warming limit. They produce policy-relevant science and analysis on climate impacts, the energy transition, adaptation and loss and damage.

**Comment by VeckoTheGecko** [comment]
Updated the tags to remove the `📚 Knowledge Hubs` tag (which is reserved for resources which centralise links like we do here). I need to update the documentation with this nuance
