### ISSUE TITLE
[RESOURCE] NASA Earth Information Center

### ISSUE THREAD

**Issue by themonarchofsquarks** [ClimateTown/knowledge-hub#315]
### Resource title

NASA Earth Information Center

### URL

https://gis.earthdata.nasa.gov/portal/apps/sites/#/earth-information-center

### Relevant tags (1 per line)

Education
Climate Models

### Resource Summary

This is the online version of NASA's Earth Information Center in Washington DC, it provides tools to visualize and interpret agriculture, air pollution, biodiversity, disasters, energy, greenhouse gases, sea level rise, water resources, and wildfires.

**Comment by VeckoTheGecko** [comment]
Small edit, but I think the Climate Journalism might be a loose fit with the other Climate Journalism resources (which create articles reporting on climate news). Let me know if I'm missing something and Climate Journalism is a good fit. Updating for the timebeing :)
