### ISSUE TITLE
[RESOURCE] U.S. National Academies interactive guide to decarbonization

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#354]
### Resource title

US National Academies: 2023 Decarbonization Guide

### URL

https://nap.nationalacademies.org/resource/25931/interactive/

### Relevant tags (1 per line)

Research
Politics/US
Education

### Resource Summary

The "Accelerating Decarbonization in the United States" report provides a comprehensive set of actionable recommendations to help policymakers achieve a just and equitable energy transition over the next decade and beyond, including policy, technology, and societal dimensions.

### Relevance

The National Academies’ 2023 [report](https://nap.nationalacademies.org/catalog/25931) on decarbonizing the U.S. has a ton of basic knowledge on climate science and policy recommendations; this collection of the report’s highlights is an excellent introduction to climate policy, and visually pleasing too.

A good introductory resource on climate action policy for newcomers

**Comment by VeckoTheGecko** [comment]
Really like the report and these more complete resources, so happy to add. I just think that there are a lot of reports out there, and adding them (+ keeping versions updated e.g. when a 2024 version comes) might cause some added overhead.

Keep them coming if you come across more, but an amazing resource instead would be a separate intiative/actively managed database that collates reports like these into one place. If you find such a project please let us know!

(ps. sorry about the late response on this, looking at onboarding resources etc once a month :) )
