### ISSUE TITLE
[RESOURCE] Citizens' Climate Lobby contact congress

### ISSUE THREAD

**Issue by Stephen-at-Pleno** [ClimateTown/knowledge-hub#377]
### Resource title

Contact congress through Citizens' Climate Lobby

### URL

https://citizensclimatelobby.org/get-loud-take-action/

### Relevant tags (1 per line)

Contacting representatives
Politics/US
Individual Action

### Resource Summary

A website making it easy to to email (or call) your legislators in Congress to push for policy action to address climate change. Featured policies include carbon fee and dividend, clean energy permitting reform, building electrification, healthy forests.

**Comment by VeckoTheGecko** [comment]
Thanks for the suggestion! We already have https://citizensclimatelobby.org as a resource (onboarded in issue #21, PR #60). Although the tags and URL before weren't as good as they could be.
