### ISSUE TITLE
[RESOURCE] Environmental Voter Project

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#380]
### Resource title

Environmental Voter Project

### URL

https://www.environmentalvoter.org/

### Relevant tags (1 per line)

Politics/US
Individual Action

### Resource Summary

A project that identify inactive environmentalists and transform them into consistent voters to build the power of the environmental movement.

**Comment by JarrodBaniqued** [comment]
_identifies_, not "identify"
