### ISSUE TITLE
[RESOURCE] Follow This

### ISSUE THREAD

**Issue by Lasercar** [ClimateTown/knowledge-hub#388]
### Resource title

Follow This

### URL

https://www.follow-this.org/

### Relevant tags (1 per line)

Finance
Collective Action
Organizations

### Resource Summary

Follow This is a grassroots non-profit organization with over 10,000 members. Based in Amsterdam, the organization empowers responsible shareholders to push Big Oil to go green.

**Comment by VeckoTheGecko** [comment]
Looks good! Updated the description to add a bit more context
