### ISSUE TITLE
[RESOURCE] ClimateTechList

### ISSUE THREAD

**Issue by Lasercar** [ClimateTown/knowledge-hub#389]
### Resource title

ClimateTechList

### URL

https://www.climatetechlist.com/

### Relevant tags (1 per line)

Climate Tech
Climate Careers

### Resource Summary

ClimateTechList is a comprehensive public climate tech jobs database for tech and non-tech professionals looking to work on climate change.

**Comment by stevenqzhang** [comment]
Thanks for this suggestion @Lasercar - I'm the creator. Let me know if there's anything i can do to help here

**Comment by VeckoTheGecko** [comment]
Looks like a great project! Thanks for the contribution (and for creating it @stevenqzhang ). I have slightly updated the resource description to remove bias.

I was just wondering (in your opinion) how does the job board differ from other job boards (ClimateBase, Terra.do, etc) @stevenqzhang ? If its similar, thats ok, just want to make sure to highlight any significant differences in the description if they are there :) .

I'm back from my break, so am back to actively maintaining this project.

**Comment by stevenqzhang** [comment]
Thanks! 

The big differences with ClimateTechList are

1. No login required for viewing any jobs/doing any searches- everything is public
2. Most number of companies/jobs out of all the climate/clean tech/green jobs job boards out there (~35,000 live job openings from 1,000 companies at a given time)
3. Everything in one giant table https://www.climatetechlist.com/jobs for ease of searching

LMK if you need more info from me!
