### ISSUE TITLE
[RESOURCE] Your Daily Dose of Climate Hope by Climate Action Now

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#398]
### Resource title

Your Daily Dose of Climate Hope

### URL

https://climateactapp.substack.com/

### Relevant tags (1 per line)

Climate Journalism
Politics

### Resource Summary

A newsletter sharing the most inspirational stories in climate action policy and beyond, from the makers of the Climate Action Now app.

### Relevance

It’s another news outlet. To quote their mission statement: “Action is the antidote to despair. Subscribe now to get one easy action to take every day, along with stories about the trends, innovations, and people creating a better world!”

**Comment by VeckoTheGecko** [comment]
@JarrodBaniqued I have removed the following tags:
- Collective Action
- Contacting representatives

I'd like to keep those tags more for tools to help contact representatives and for orginisations/initiatives that people can get involved in. A news source may have some overlap there, but it wouldn't be a main focus.

I have also added #404 after hearing about Climate Action now, let me know what you think :)
