### ISSUE TITLE
[BUG] Chrome and Edge stall waiting for Twemoji files

### ISSUE THREAD

**Issue by EdwardPrado** [ClimateTown/knowledge-hub#400]
**Describe the bug**
MaxCDN, the host for Twemoji, [has shutdown](https://github.com/twitter/twemoji/issues/580).  In Chrome and Edge (and likely other Chromium browsers) this results in the web page not loading as it waits on the Twemoji requests.  This does not happen with Firefox, which immediately has an error returned.  The screenshots below show the wait time ranging from 20 to 30 seconds.

**Network Screenshots:**
Chrome
![image](https://github.com/user-attachments/assets/89ebed32-af67-4f71-ac70-2612daff1d9d)
Edge
![image](https://github.com/user-attachments/assets/e59f50b6-c9a4-4b2a-94c0-c701c02c0400)
Firefox
![image](https://github.com/user-attachments/assets/c22f4ffa-7001-4f66-9531-b5341e9d95bd)

**To Reproduce**
Steps to reproduce the bug:

1. (Optional) Open Chrome devtools to monitor network traffic
2. Go to https://hub.climatetownproductions.com/ in Chrome or Edge
3. Wait for the page to load
4. (Optional) Check the network requests for the Twemoji min files

**Expected behavior**
Page should not be stalling as it waits on the minimized Twemoji files.

**Additional comments**
Twemoji will be removed as part of the Redesign (#70) since emojis aren't used in the new design.  Till that's done and the redesign branch is merged with main I suspect this will dissuade users from using the site.

**Comment by VeckoTheGecko** [comment]
Thanks for the report! I didn't notice this (1 year later 😵). Just updated the CDN.
