### ISSUE TITLE
[FEATURE] OG meta tags

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#66]
**Describe your suggested improvement**
Add [OG meta tags](https://ahrefs.com/blog/open-graph-meta-tags/) to customise how the knowledge hub looks when linked on social media.

**Describe the benefit**
Refines the look of the knowledge hub, making it a more accessible resource.

**Would you be capable/willing to implement the improvement?**
Yes 🙂 (although would need some help coming up with an image to put for the image tag)

**Comment by dmlb** [comment]
reuse the book stack image?

**Comment by VeckoTheGecko** [comment]
Wild, was just working on this PR. Got another one in mind that uses real-estate better 😄 

![knowledge-hub-image](https://github.com/ClimateTown/knowledge-hub/assets/36369090/42c74ca8-2d68-4089-8b96-fd5307921707)
