### ISSUE TITLE
[RESOURCE ONBOARDING] Preventing food waste

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#72]
| **Resource Title**      | **URL**                    | **Tags**                     | **Summary**                                                                                                                                                                                              |
|----------------|----------------------------|------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Too Good to Go | https://toogoodtogo.com/   | Food Waste, location/US, location/Canada      | Too Good To Go helps connects restaurants and stores to their local community to reduce food waste nearing their best before date. Founded in 2016 in Copenhagen, Too Good to Go is now in 17 countries. |
| Flash Food     | https://www.flashfood.com/ | Food Waste, location/Global| Use Flash Food to prevent food waste, and get savings on fresh food items nearing their best before date in Canada and the U.S.                                                                          |                                                                                                                                                                                       
| Love Food Hate Waste Guide | https://lovefoodhatewaste.ca/a-z/ | Food Waste | Prevent food waste with Love Food Hate Waste, and their ultimate A-Z food storage and usage guide. |

**More notes**
Cheers to `mks` for first starting this discussion in the Discord
https://discord.com/channels/897926845088014377/945697978721656882/1078001579304697886

Open to anyone to post in the comments here more resources on preventing food waste.

**Comment by dmlb** [comment]
https://lovefoodhatewaste.ca/a-z/
food storage and preserving tips

**Comment by VeckoTheGecko** [comment]
Thanks for the suggestion @dmlb! Have updated the table. Will onboard this weekend.
