### ISSUE TITLE
[FEATURE] All Contributors support

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#82]
**Describe your suggested improvement**
Better recognise contributors by using the all contributors bot.  
https://allcontributors.org/

Surface either in `README.md` or perhaps in section on the website.

**Would you be capable/willing to implement the improvement?**
~~Yes~~ Not without some help (https://github.com/ClimateTown/knowledge-hub/issues/82#issuecomment-1540375395)

**Comment by VeckoTheGecko** [comment]
Still buggy as per comments in #85 😢

**Comment by VeckoTheGecko** [comment]
@Morzaram would you mind syncing your fork and trying this there?

ie.
- install the `all-contributors` bot on your fork
- make an issue in your fork, and type "@all-contributors please add @Morzaram for code" or some other usage
- bot should reply in the issue

---
If it fails, it may be to do with the files in the repo and I can bugfix. If it succeeds, its a weird bug beyond our control as per the referenced issue just above.

No need for you to bugfix (its a headache lol)

**Comment by Morzaram** [comment]
@VeckoTheGecko https://github.com/Morzaram/knowledge-hub/issues/1

**Comment by VeckoTheGecko** [comment]
@Morzaram I dont think thats the issue. From what I see that doesn't change anything significant:
![image](https://user-images.githubusercontent.com/36369090/227706706-200810d6-04e7-48bc-8bed-20ed7df127ed.png)

Thanks for testing :)

**Comment by Morzaram** [comment]
Yea true! And no problem! Let me know if there's anything else I can do!

**Comment by VeckoTheGecko** [comment]
More people are starting to contribute to this project, and I would really like to get All Contributors up and running so that we can recognise contributions in the README.

My attempts to get this working have been frustrating and messy, encountering this strange bug #460. If anyone is able to suss out exactly what the problem is, that will allow us to get this up and running in this repo.

**Comment by VeckoTheGecko** [comment]
Fixed the bot! Turns out the problem was that we had a `all-contributors` branch in the repo which contflicted with the bot which uses the `all-contributors/*` namespace. -1 for uninformative bot error messages I guess 😂

**Comment by VeckoTheGecko** [comment]
@all-contributors
please add @VeckoTheGecko for maintenance, project management, ideas, coding, and content
please add @azebramoomoo for content, and design
please add @Jacobjeevan for code
please add @Morzaram for code
please add @JarrodBaniqued for content
please add @dmlb for accessibility
please add @tutterown for code and content
please add @GBT7 for content
please add @williamtaggart97 for ideas
please add @Micahg05 for code

**Comment by VeckoTheGecko** [comment]
Sorry for the repeated pings people 😢 
@all-contributors
please add @VeckoTheGecko for maintenance, project management, ideas, coding, and content
please add @azebramoomoo for content, and design
please add @Jacobjeevan for code
please add @Morzaram for code
please add @JarrodBaniqued for content
please add @dmlb for accessibility
please add @tutterown for code and content
please add @GBT7 for content
please add @williamtaggart97 for ideas
please add @Micahg05 for code
