### ISSUE TITLE
[RESOURCE] OneArmy

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#91]
### Resource title

OneArmy

### URL

https://www.onearmy.earth/

### Relevant tags (1 per line)

Collective Action
Discord
Community

### Resource Summary

One Army is a movement tackling global problems. Centered on open source, and with an active Discord community, One Army runs Precious Plastic, Project Kamp, Fixing Fashion and Phonebloks.

### Relevance

Great, earth focussed community that ClimateTown members might want to be a part of.

**Comment by tutterown** [comment]
Since this has the `approved` label, does this just need to be added to the resources.yml file? Or is there more that needs to be done to add a resource that I'm missing?

**Comment by VeckoTheGecko** [comment]
Yes. It just needs to be added to the resources.yml. I'm working on automated tooling to help with onboarding (ie. A small app that pulls from the GitHub API and fills in the yml) so I've been delaying a little.

Welcome to send a PR if you want though 😁

**Comment by tutterown** [comment]
PR submitted https://github.com/ClimateTown/knowledge-hub/pull/110
