### ISSUE TITLE
[FEATURE] Resource Analytics

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#96]
**Describe your suggested improvement**
Add traffic analytics to the resources to track which resources are popular and less popular (and generally track activity on the site).

**Describe the benefit**
Allows for better measurement of the health of the site, its impact, and the impact of individual resources.

**Would you be capable/willing to implement the improvement?**
No. Enough on my plate at the moment, and this is outside my domain of expertise. Happy for someone else to take a look at this

**Additional comments**
Care needs to be taken with analytics provider. I've heard that Google Analytics doesn't respect privacy (although I'm not sure about the details). Good to dicsuss here first about which one we should use.

The analytics dashboards and raw data will be private to the Knowledge Hub moderators.

**Comment by dmlb** [comment]
Does it need to be free?

Some options:

https://www.openwebanalytics.com/
- open source
- https://github.com/Open-Web-Analytics/Open-Web-Analytics

https://plausible.io/
- open source
- [script weighs less than 1 KB](https://plausible.io/lightweight-web-analytics)
- compliant with GDPR, CCPA and PECR
- own your data, data encrypted and stored in EU (Germany)
- no personal identifiers, cookies, cross-site/device tracking
- starts at 9$/month

https://www.simpleanalytics.com/
- compliant with GDPR, PECR, CCPA and more
- own your data, data encrypted and stored in EU
- [no personal identifiers, cookies](https://docs.simpleanalytics.com/what-we-collect)
- starts at 9$/month

https://usefathom.com/
- fast script (doesn't give size in kb)
- compliant with GDPR, CCPA, ePrivacy, PECR (and more)
- own your data
- no cookies, [anonymized hash](https://usefathom.com/blog/anonymization)
- starts at 14$/month

https://clarity.microsoft.com/
- compliant with GDPR, CCPA
- [open source](https://github.com/microsoft/clarity)
- no sampling
- [always free](https://clarity.microsoft.com/pricing)

https://clicky.com/
- compliant with GDPR
- anonymized IP addresses, [cookies only used with user consent](https://clicky.com/help/faq/privacy)
- [free version available](https://clicky.com/compare/)

https://piwik.pro/
- compliant with GDPR in the EU, LGPD in Brazil and CCPA, HIPAA in the US
- [free core plan](https://piwik.pro/core-plan/)

https://mixpanel.com/
- compliant with major laws like GDPR, CCPA, PDPA, LGPD
- EU data residency optional
- data encryption
- [free 20M events starter](https://mixpanel.com/pricing/)

**Comment by VeckoTheGecko** [comment]
Thanks for the thorough overview @dmlb ! Thinking about it, I don't think data privacy is a huge issue (the data in itself isn't particularly sensitive). Then Google Analytics would also be an option to consider. Keen to hear others' takes if they disagree.

I think in order of importance:
1. Price (free, or permissive, and periodically resetting free tier)
2. Ease of use
  - Self hosted is an option (using a cloud service providers free tier) but I'd prefer a standalone service to reduce complexity
3. Monitoring capacity (is it enough to capture reasonable use of the website?)
4. Privacy

The main items we're interested in are clicks to the different resource cards, though other analytics are welcome.

With those in mind:
- 🤔 https://www.openwebanalytics.com Self hosted
- ❌ https://plausible.io/
- ❌ https://www.simpleanalytics.com/

- ❌ https://usefathom.com/

- ✅ https://clarity.microsoft.com/


- ✅ https://clicky.com/
- ✅ https://piwik.pro/
- ✅ https://mixpanel.com/


I think MixPanel looks to be the best of the lot? Good privacy, permissive free tier with 20M/month events (Clicky is 3,000 page views/day, piwik is 500,000 a month). Microsoft Clarity and Google Analytics can still be options
