### ISSUE TITLE
[RESOURCE] Distilled by Michael Thomas

### ISSUE THREAD

**Issue by JarrodBaniqued** [ClimateTown/knowledge-hub#99]
### Resource title

Distilled by Michael Thomas

### URL

https://www.distilled.earth/

### Relevant tags (1 per line)

Climate Journalism

### Resource Summary

Deeply researched stories about the politics of climate change. Written by Michael Thomas.

### Relevance

Contains a host of bold, concise overviews of climate policy in the US and abroad, plus excellent collaborations with Emily Atkin on following the money

**Comment by VeckoTheGecko** [comment]
Great suggestion (love the new tag too).

Made some edits to your post (note that the `resource summary` section is the one that is used in the website on the cards, so is good to keep timeless).
